[sweep]
gate_delay_start=0
gate_delay_stop=1000
pmt_dac_start=0
pmt_dac_stop=0
steps=10
telemetry=true

[readout_settings]
windows=8
lookback=16
write_after_trig=16
num_captures=10

[pmt_dac]
address=0x00
channel=0
